"""empty message

Revision ID: 4113a638fb78
Revises: None
Create Date: 2015-06-22 17:12:44.325000

"""

# revision identifiers, used by Alembic.
revision = '4113a638fb78'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###  
    op.create_table('agent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('fullName', sa.Unicode(length=255), nullable=True),
    sa.Column('imgUrl', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('agent_handle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agentId', sa.INTEGER(), nullable=True),
    sa.Column('handleName', sa.Unicode(length=255), nullable=True),
    sa.Column('handleType', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agentId'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agentId', sa.INTEGER(), nullable=False),
    sa.Column('protocol', sa.Unicode(length=255)),
    sa.Column('name', sa.Unicode(length=255)),
    sa.Column('description', sa.Unicode(length=255)),
    sa.ForeignKeyConstraint(['agentId'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )   
    op.create_table('agent_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agentId', sa.INTEGER(), nullable=True),
    sa.Column('groupId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['agentId'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['groupId'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
  
    op.create_table('network',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agentId', sa.INTEGER(), nullable=False),
    sa.Column('groupId', sa.INTEGER(), nullable=False),
    sa.Column('protocol', sa.Unicode(length=2000)),
    sa.Column('tokenName', sa.Unicode(length=60)),
    sa.Column('name', sa.Unicode(length=255)),
    sa.Column('description', sa.Unicode(length=255)),
    sa.Column('tokenSymbol', sa.Unicode(length=3)),
    sa.Column('comment', sa.Unicode(length=2000)),
    sa.Column('tokenTotal', sa.INTEGER()),
    sa.Column('status', sa.Unicode(length=100), nullable=True),
    sa.Column('similarEvaluationRate', sa.INTEGER()),
    sa.Column('passingResponsibilityRate', sa.INTEGER()),
    sa.ForeignKeyConstraint(['agentId'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['groupId'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )   
    op.create_table('agent_network',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agentId', sa.INTEGER(), nullable=True),
    sa.Column('networkId', sa.INTEGER(), nullable=True),
    sa.Column('tokens', sa.FLOAT(), nullable=True),
    sa.Column('reputation', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['agentId'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['networkId'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('network_handle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('networkId', sa.INTEGER(), nullable=True),
    sa.Column('handleName', sa.Unicode(length=255), nullable=True),
    sa.Column('handleType', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['networkId'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribution',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agentId', sa.INTEGER(), nullable=True),
    sa.Column('agentNetworkId', sa.INTEGER(), nullable=True),
    sa.Column('timeCreated', sa.DATETIME(), nullable=True),
    sa.Column('type', sa.Unicode(length=340), nullable=True),
    sa.Column('status', sa.Unicode(length=100), nullable=True),
    sa.Column('currentValuation', sa.FLOAT(), nullable=True),
    sa.Column('valueIndic', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.Unicode(length=10000), nullable=True),
    sa.Column('comment', sa.Unicode(length=2000)),
    sa.ForeignKeyConstraint(['agentId'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['agentNetworkId'], ['agent_network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    
    op.create_table('contribution_contributor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contributionId', sa.INTEGER(), nullable=True),
    sa.Column('contributorId', sa.INTEGER(), nullable=True),
    sa.Column('percentage', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['contributionId'], ['contribution.id'], ),
    sa.ForeignKeyConstraint(['contributorId'], ['agent_handle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    
    op.create_table('contributionValue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contributionId', sa.INTEGER(), nullable=True),
    sa.Column('agentNetworkId', sa.INTEGER(), nullable=True),
    sa.Column('agentId', sa.INTEGER(), nullable=True),
    sa.Column('reputationGain', sa.FLOAT(), nullable=True),
    sa.Column('reputation', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['agentId'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['contributionId'], ['contribution.id'], ),
    sa.ForeignKeyConstraint(['agentNetworkId'], ['agent_network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    
    op.create_table('evaluation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agentId', sa.INTEGER(), nullable=True),
    sa.Column('contributionId', sa.INTEGER(), nullable=True),
    sa.Column('tokens', sa.FLOAT(), nullable=True),
    sa.Column('stake', sa.FLOAT(), nullable=True),
    sa.Column('reputation', sa.FLOAT(), nullable=True),
    sa.Column('contributionValueAfterEvaluation', sa.FLOAT(), nullable=True),
    sa.Column('timeCreated', sa.DATETIME(), nullable=True),
    sa.Column('comment', sa.Unicode(length=2000)),
    sa.ForeignKeyConstraint(['contributionId'], ['contribution.id'], ),
    sa.ForeignKeyConstraint(['agentId'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation')
    op.drop_table('contributionValue')
    op.drop_table('contribution_contributor')
    op.drop_table('contribution')
    op.drop_table('agent_network')
    op.drop_table('network_handle')
    op.drop_table('network')
    op.drop_table('group')
    op.drop_table('agent_group')
    op.drop_table('handle')
    op.drop_table('agent_handle')
    op.drop_table('agent')
    
    
    ### end Alembic commands ###
